# Project information
site_name: Package name
site_url: https://hubisan.github.io/emacs-template-package/
site_author: John Doe
site_description: >-
    Multiline desription for this package. Quite nice and so on. Multiline
    desription for this package.

# Repository
repo_url: https://github.com/hubisan/emacs-template-package
edit_uri: ""

# Copyright
copyright: Copyright &copy; 20xx - 20xx John Doe

# Configuration
theme:
    name: material

    # 404 page
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    # features:
    #- tabs
    #- instant
    palette:
        scheme: emacs
        primary: emacs
        accent: emacs
    font:
        text: Roboto
        code: Roboto Mono
    favicon: favicon.png
    logo: img/logo.svg

# Customization
extra_css:
    - css/extra.css
extra_javascript:
    - js/extra.js

# Plugins
plugins:
    - search
    - git-revision-date-localized
    - minify:
          minify_html: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.smarty:
          smart_angled_quotes: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: repo-user
      repo: repo-name
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
    - Overview: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Customization: customization.md
    - Key Bindings: key-bindings.md
    - Changelog: changelog.md
    - Contributing: contributing.md
